# Generated by Django 4.2.5 on 2023-10-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ROs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data_criacao', models.DateField()),
                ('data_vencimento', models.DateField()),
            ],
        ),
    ]
